/**
 * @brief	Allegro.h 
 * @note	Project inspired by Allegro Game Library (4.4.2) created by Shawn Hargreaves.
 *			http://liballeg.org/stabledocs/en/allegro.html
 *			API : https://www.allegro.cc/manual/4/api/
 *
 */

#ifndef _ALLEGRO_H
#define _ALLEGRO_H

#include "HDMI/Ch703x.h"
#include "Bitmap.h"
#include "Blit.h"
#include "Sprite.h"

/**
 * @brief 	Video generated by RA8876. Monitors with DVI input accept only constant GFX_xxx_DVI as parameter.<br>
 *			Monitor/HDTV with HDMI interface accepts both GFX_xxx_DVI & GFX_xxx_HDMI as parameter.<br>
 */
enum GFX_VIDEO_MODE{			//RA8876  -> CH7035B
		GFX_AUTO_DETECT = 0,	//CEA 1280x720p -> CEA 1280x720p HDMI using 9904 bootROM
		GFX_VGA_SVGA_DVI,		//640x480 -> 800x600 DVI
		GFX_WVGA_WXGA_DVI,		//800x480 -> 1280x768 DVI		
		GFX_SVGA_XGA_DVI,		//800x600 -> 1024x768 DVI
		GFX_SVGA_SXGA_DVI,		//800x600 -> 1280x960 DVI
		GFX_SVGA_UXGA_DVI,		//800x600 -> 1600x1200 DVI
		GFX_HD480p_HD720p_DVI,	//CEA 720x480p -> CEA 1280x720p DVI
		GFX_HD720p_HD1080p_DVI,	//CEA 1280x720p -> 1920x1080p DVI
		
		GFX_FWVGA_HD720p_HDMI,	//848x480 -> CEA 1280x720p HDMI		
		GFX_HD480p_HD720p_HDMI,	//CEA 720x480p -> CEA 1280x720p HDMI
		GFX_HD576p_SXGA_HDMI,	//CEA 720x576p -> 1280x1024 DVI
		GFX_HD720p_HD1080i_HDMI,//CEA 1280x720p -> 1920x1080i HDMI
		GFX_HD720p_HD1080p_HDMI,//CEA 1280x720p -> 1920x1080p HDMI
		
		GFX_WQVGA_HD480p_HDMI,	//480x272 -> CEA 720x480p HDMI
		GFX_WQVGA_HD720p_HDMI,	//480x272 -> CEA 1280x720p HDMI 
		GFX_WQVGA_HD1080p_HDMI	//480x272 -> CEA 1920x1080p HDMI
};

/**
 * @note	VIRTUAL_W & VIRTUAL_H are parameters that return Canvas Width and Height after set_gfx_mode() is called.<br>
 *			Canvas Width and Height parameterize the image buffer allocated in SDRAM of RA8876. 
 */
#define VIRTUAL_W	ra8876lite.getCanvasWidth()
#define VIRTUAL_H	ra8876lite.getCanvasHeight()

/**
 * @note	SCREEN_W & SCREEN_H are width and height of the RGB video generated by RA8876.<br>
 *			These parameters may not the same as the final video output on LCD monitor.<br>
 *			Because there is a HDMI encoder (CH7035B) with scaling engine onboard of ArduoHDMI,<br>
 *			the actual video resolution output from CH7035B is scaled by a certain factor parameterized by <br>
 *			the argument in calling HDMI_Tx.init(). For example, calling the function <br>
 *			HDMI_Tx.init(VIDEO_in_848x480_out_HDMI_720p_60Hz)<br>
 *			will scale a 848x480 video source to an HDMI output of 1280x720 @ 60Hz. <br>
 *			CH7035B allows us to design graphics on a smaller video canvas (say 848x480) and get it boosted <br>
 *			to a higher resolution of 1280x720 and get it displayed on a modern HD or Full HDTV.<br>		
 */
#define SCREEN_W		ra8876lite.getLCDWidth()
#define SCREEN_H		ra8876lite.getLCDHeight()


/* Starts C function definitions when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

int 	allegro_init(void);
void	allegro_exit(void);
void 	set_color_depth(int depth);
int 	set_gfx_mode(int card, int v_w, int v_h);
#ifdef __cplusplus
}
#endif	
/* Ends C function definitions when using C++ */

#endif	//_ALLEGRO_H